---
title: "CenSoc Multiple Cohorts"
---

Summary: Run STAN code on real CenSoc data. 

We also test whether dropping first and last death age for each cohort affects results. Note these endpoints contain only half true number of deaths due to truncation / lexis triangle subtlety. 

```{r}
#setwd("/hdir/0/mariaosborne/censoc")
library(rstan)
library(flexsurv)
library(tidyverse)
library(bayesplot)
library(scales)
library(rstanarm)
library(data.table)
library(cowplot)
source('../gompertz_functions.R')

## path on server 
## numident <- fread("/data/josh/CenSoc/data_release_v2/censoc_numident_v2/censoc_numident_v2.csv")

## Local path 
numident <- fread("~/Documents/data/censoc_numident_v2/censoc_numident_v2.csv")
```

```{r}
mc_fe_trunc_model_text = "
functions {
  real get_alpha(real mode, real beta) {
    real alpha = beta/exp(mode*beta);
    return(alpha);
  }

  real gompertz_lpdf(real x, real mode, real beta){
    real alpha = get_alpha(mode, beta);
    real prob = alpha * exp(beta*x) * exp((-alpha/beta) * (exp(beta*x)-1));
    return log(prob);
  }
 
  real gompertz_lcdf(real x, real mode, real beta){
    real alpha = get_alpha(mode, beta);
    real cdf = 1 - exp((-alpha/beta)*(exp(beta*x)-1));
    return log(cdf);
  }

  real gompertz_lccdf(real x, real mode, real beta){
    real alpha = get_alpha(mode, beta);
    real ccdf = exp((-alpha/beta)*(exp(beta*x)-1));
    return log(ccdf);
  }
 
}

data {
  int N;                   // number of observations
  real L[N];               // lower truncation bound 
  real U[N];               // upper truncation bound 
  int cohort_index[N];    // a way to assign cohorts to certain numbers
  int num_cohorts;         // number of cohorts included in the data set.
  real<lower=0> x[N];      // observed ages at death
}

parameters {
  real<lower=0> mode[num_cohorts];       // modal age at death param (a vector)
  real<lower=0.001> beta;   // 'force of mortality' param (a vector)
}

model {
  for (i in 1:N) {
     if (x[i] < L[i] || x[i] > U[i]) {
          target += negative_infinity();
     }
     else {
          target += log_diff_exp(gompertz_lcdf(x[i]+1|mode[cohort_index[i]], beta),
                                gompertz_lcdf(x[i]|mode[cohort_index[i]],beta)) -
                    log_diff_exp(gompertz_lcdf(U[i]| mode[cohort_index[i]], beta),
                                gompertz_lcdf(L[i] | mode[cohort_index[i]], beta));
     }}
  mode ~ uniform(60, 100);                     // prior for m (we will have priors be all the same regardless of cohort)
  beta ~ uniform(0.001, 0.3);                 // prior for beta
}"

number_of_cohorts <- 10 
multicohort_fe_model = stan_model(model_code = mc_fe_trunc_model_text,
                   model_name='fixed effects gompertz with multiple cohorts, common beta')

init_multicohort_fe_model <- function () {list(beta=0.08, mode=rep(75, number_of_cohorts))} 
```

```{r}
numident_data <- numident %>% 
  filter(byear %in% 1910:1919) %>% 
  select(HISTID, byear, dyear, death_age) %>% 
  mutate(upper = 2005 - byear + 1,
         lower = 1988 - byear,
         cohort_index = byear - 1909) %>% 
  sample_n(5000)

# Put the data in a list for Stan input
censoc_data <- list(x = numident_data$death_age,
            N = nrow(numident_data),
            num_cohorts = number_of_cohorts,
            L = numident_data$lower,
            U = numident_data$upper,
            cohort_index = numident_data$cohort_index)

# Fixed effects model
fe_fit_test1 = sampling(object = multicohort_fe_model, 
                        data = censoc_data,
                        init = init_multicohort_fe_model,
                        chains = 2,
                         iter = 2000,
                        warmup = 200)


print(fe_fit_test1)
```

```{r}
## explore truncation for two cohorts. Notice death counts drop by 50% for edge points. We need to adjut for this. 
numident %>% 
  filter(byear %in% 1915:1916) %>%
  count(byear, death_age) %>%
  ggplot(aes(x = death_age, y = n, group = byear)) + geom_point() + geom_line(aes(linetype = as.factor(byear))) + ylim(0, 21000) + theme_cowplot()
```

```{r}
## drop minimum and maximum death age
numident_data <- numident %>% 
  filter(byear %in% 1910:1919) %>% 
  select(HISTID, byear, dyear, death_age) %>% 
  group_by(byear) %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  ungroup() %>% 
  mutate(upper = 2005 - byear + 1,
         lower = 1988 - byear,
         cohort_index = byear - 1909) %>% 
  sample_n(1000)

 
# Put the data in a list for Stan input
censoc_data <- list(x = numident_data_adjusted$death_age,
            N = nrow(numident_data_adjusted),
            num_cohorts = number_of_cohorts,
            L = numident_data_adjusted$lower,
            U = numident_data_adjusted$upper,
            cohort_index = numident_data_adjusted$cohort_index)

# Fixed effects model
fe_fit_test2 = sampling(object = multicohort_fe_model, 
                        data = censoc_data,
                        init = init_multicohort_fe_model,
                        chains = 2,
                         iter = 2000,
                        warmup = 200)

print(fe_fit_test2) 
```





